
---
- name: copy backend files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /root/project/backend/

- name: Extract backend files
  become: true
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
- name: start app 
  become: true
  shell: |
    cd ~/backend
    sudo npm install
    pm2 stop default
    pm2 start npm -- start